const express = require('express')
const router = express.Router()
const multer = require('multer')
const userSignUpController = require("../controller/user/userSignUp")
const userSignInController = require('../controller/user/userSignIn')
const userDetailsController = require('../controller/user/userDetails')
const userLogout = require('../controller/user/userLogout')
const allUsers = require('../controller/user/allUsers')
const updateUser = require('../controller/user/updateUser')
const deleteUser = require('../controller/user/deleteUser')
const forgotPassword = require('../controller/user/forgotPassword')
const verifyOTP = require('../controller/user/verifyOTP')
const changePassword = require('../controller/user/changePassword')
const addToCartController = require('../controller/user/addToCartController')
const countAddToCartProduct = require('../controller/user/countAddToCartProduct')
const addToCartViewProduct = require('../controller/user/addToCartViewProduct')
const updateAddToCartProduct = require('../controller/user/updateAddToCartProduct')
const deleteAddToCartProduct = require('../controller/user/deleteAddToCartProduct')
const UploadProductController = require('../controller/product/uploadProduct')
const getProductController = require('../controller/product/getProduct')
const updateProductController = require('../controller/product/updateProduct')
const deleteProductController = require('../controller/product/deleteProduct')
const getCategoryProduct = require('../controller/product/getCategoryProductOne')
const getCategoryWiseProduct = require('../controller/product/getCategoryWiseProduct')
const getProductDetails = require('../controller/product/getProductDetails')
const searchProduct = require('../controller/product/searchProduct')
const filterProduct = require('../controller/product/filterProduct')
const getFeaturedProduct = require('../controller/product/getFeaturedProduct')
const getBestSellingProduct = require('../controller/product/getBestSellingProduct')
const getHomeCategoryProduct = require('../controller/product/getHomeCategoryProduct')
const addReview = require('../controller/product/addReview')
const allReviews = require('../controller/product/getAllReviews')
const deleteReview = require('../controller/product/deleteReview')
const placeOrderController = require('../controller/order/placeOrder')
const allOrder = require('../controller/order/allOrder')
const uploadImageToDb = require('../controller/image/uploadImage')
const getImage = require('../controller/image/getImage')
const getAllImages = require('../controller/image/getAllImages')
const authToken = require('../middleware/authToken')
const storage = multer.memoryStorage()
const upload = multer({ storage: storage })

// --- Routes ---

// Health check endpoint for testing connectivity
router.get("/health", (req, res) => {
    res.json({
        status: "OK",
        message: "Backend server is running and accessible",
        timestamp: new Date().toISOString(),
        origin: req.headers.origin || "No origin header"
    })
})

router.post("/signup", userSignUpController)
router.post("/signin", userSignInController)
router.get("/user-details", authToken, userDetailsController)
router.get("/userLogout", userLogout)
router.post("/forgot-password", forgotPassword)
router.post("/verify-otp", verifyOTP)
router.post("/change-password", changePassword)
router.get("/all-user", authToken, allUsers)
router.post("/update-user", authToken, updateUser)
router.post("/delete-user", authToken, deleteUser)
router.post("/upload-product", authToken, UploadProductController)
router.get("/get-product", getProductController)
router.post("/update-product", authToken, updateProductController)
router.post("/delete-product", authToken, deleteProductController)
router.get("/get-categoryProduct", getCategoryProduct)
router.post("/category-product", getCategoryWiseProduct)
router.post("/product-details", getProductDetails)
router.get("/search", searchProduct)
router.post("/filter-product", filterProduct)
router.get("/get-featured-product", getFeaturedProduct)
router.get("/get-best-selling-product", getBestSellingProduct)
router.post("/get-home-category-product", getHomeCategoryProduct)
router.post("/addtocart", authToken, addToCartController)
router.get("/countAddToCartProduct", authToken, countAddToCartProduct)
router.get("/view-card-product", authToken, addToCartViewProduct)
router.post("/update-cart-product", authToken, updateAddToCartProduct)
router.post("/delete-cart-product", authToken, deleteAddToCartProduct)
router.post("/place-order", authToken, placeOrderController)
router.get("/all-orders", authToken, allOrder)
router.post("/add-review", authToken, addReview)
router.get("/all-reviews", allReviews)
router.post("/delete-review", authToken, deleteReview)
router.post("/upload-image", authToken, upload.single('image'), uploadImageToDb)
router.get("/image/:id", getImage)
router.get("/images", getAllImages)


module.exports = router