const productModel = require("../../models/productModel")

const getAllReviewsController = async(req,res)=>{
    try{
        const allReviews = await productModel.find({}, {
            productName: 1,
            category: 1,
            productImage: 1,
            reviews: 1
        }).sort({ createdAt: -1 })

        // Flatten the reviews to make them easier to display in a table
        let flatReviews = []
        allReviews.forEach(product => {
            if(product.reviews && product.reviews.length > 0){
                product.reviews.forEach(review => {
                    flatReviews.push({
                        _id: review._id, // Review ID (if generated by subdocument) or we might need to rely on index if not
                        productId: product._id,
                        productName: product.productName,
                        category: product.category,
                        productImage: product.productImage[0],
                        userName: review.userName,
                        userId: review.userId,
                        rating: review.rating,
                        comment: review.comment,
                        createdAt: review.createdAt
                    })
                })
            }
        })

        // Sort flat reviews by date descending
        flatReviews.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))

        res.json({
            message : "All reviews fetched successfully",
            data : flatReviews,
            success : true,
            error : false
        })

    }catch(err){
        res.json({
            message : err?.message || err,
            error : true,
            success : false
        })
    }
}

module.exports = getAllReviewsController
